device: cuda
dataset_args:
  d_type: train
  task_dir: ./data/data/Intra
  task_type: Intra
  normalize: True
  global_normalization: False
  zscore_normalization: True
  downsampling: False
  downsample_by: 0.5
  bounds: [0, 1]
  sequence_length: 4
  future_steps: 1
dataloader_args:
  num_workers: 16
  batch_size: 128
  shuffle: True
train_epochs: 50
evaluation: None 