device: cuda
dataset_args:
  d_type: train
  task_dir: ./data/data/Intra
  task_type: Intra
  noise: True
  normalize: True
  global_normalization: False
  zscore_normalization: True
  downsampling: True
  downsample_by: 0.8
  bounds: [0, 1]
  sequence_length: 50
dataloader_args:
  num_workers: 16
  batch_size: 1024
  shuffle: True
model_args:
  lr: 0.003
  lr_decay: 0.9
  weight_decay: 0.1
  dropout: 0.5
  lstm_layers: 1
train_epochs: 4
evaluation: None 