device: cuda
dataset_args:
  d_type: train
  task_dir: ./data/data/Intra
  task_type: Intra
  normalize: True
  global_normalization: True
  zscore_normalization: False
  downsampling: True
  downsample_by: 0.0
  bounds: [0, 1]
  sequence_length: 61
  future_steps: 1
dataloader_args:
  num_workers: 4
  batch_size: 256
  shuffle: True
train_epochs: 30
evaluation: None 