device: cuda
dataset_args:
  d_type: train
  task_dir: ./data/data/Intra
  task_type: Intra
  normalize: True
  global_normalization: False
  zscore_normalization: True
  downsampling: False
  downsample_by: 0.1
  bounds: [0, 1]
  sequence_length: 61
  future_steps: 1
dataloader_args:
  num_workers: 0
  batch_size: 4
  shuffle: True
train_epochs: 30
evaluation: None 