device: cuda
dataset_args:
  d_type: train
  task_dir: ./data/data/Intra
  task_type: Intra
  normalize: True
  global_normalization: False
  zscore_normalization: True
  downsampling: True
  downsample_by: 0.9
  bounds: [0, 1]
  sequence_length: 3562
  future_steps: 1
dataloader_args:
  num_workers: 16
  batch_size: 20
  shuffle: True
train_epochs: 30
evaluation: None 